### ISSUE TITLE
Modal key bindings?

### ISSUE THREAD

**Issue by dumblob** [cessen/led#1]
Just came across this and immediately loved the ideas from `ideas.md` file. I saw in the source that this uses non-modal key bindings.

Would you consider supporting also modal keybindings?

The idea is simple - every keybinding which needs to be currently prepended with `Ctrl` will have an identical counterpart which will work only in the alternative mode but will not need `Ctrl` to be pressed first/simultaneously :wink:.

**Comment by cessen** [comment]
Thanks for your interest.  This is very much a personal, exploratory project, though, not a real software project I intend for anyone to use.  I should probably make that clearer in the readme.

If you're looking for a real project with modal keybindings, check out [Helix](https://github.com/helix-editor/helix).  It's the editor that I actually use for coding.

**Comment by dumblob** [comment]
Ok, understood.

Btw. I came here from Helix :wink:.
